### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by d0ky** [Orbitale/EasyImpress#1]
It's just me or the demo is not working anymore?

**Comment by Pierstoval** [comment]
Yup, got a server crash some time ago, I have to fix this, and will do it tomorrow ;) Thanks for noticing by the way!

**Comment by Pierstoval** [comment]
It should be working again :D 

http://demo.orbitale.io/easy_impress/

Thanks ;)

**Comment by The-Don-Himself** [comment]
Hi @Pierstoval , I think the demos are down again :(

**Comment by Pierstoval** [comment]
Seems to be working right now 😕

**Comment by The-Don-Himself** [comment]
I'm still getting an error

 Oops! An Error Occurred
The server returned a "400 Bad Request".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by Pierstoval** [comment]
It seems to comme from the `AppCache` file, I disabled it on the demo repo, can you test again @The-Don-Himself ?

**Comment by The-Don-Himself** [comment]
I just have and all seems well, though I'm on mobile. Will check again when back on desktop just incase. Thanks.

**Comment by Pierstoval** [comment]
I'm gonna enable mobile support, because it's disabled in Impress by default IIRC :)

**Comment by Pierstoval** [comment]
@The-Don-Himself The new version is online, can you check again? Sorry for making you test so many often 😆

**Comment by The-Don-Himself** [comment]
@Pierstoval sorry for the delay in getting back... different time zones :) On the brighter side it does give you a wider base to test with, which I have and I can confirm the demo works on both desktop and mobile... and it's snappy too :+1: 

Thanks!

**Comment by Pierstoval** [comment]
Awesome! 👍 Thanks for submitting the issue 🥇
